# Generated by Django 4.1 on 2022-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='the_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
